version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 920808Ser.
      MYSQL_DATABASE: euclidiana
    ports:
      - "3308:3306"
    networks:
      - my_network

  app:
    build:
      context: ./Two-Dimensional-Classification
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/euclidiana
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 920808Ser.
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network

  angular_app:
    build:
      context: ./FRONT_ANGULAR_BASIC_API_MEDICAMENTOS
    ports:
      - "4200:4200"
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge