FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests
FROM openjdk:17-jdk
WORKDIR /app
COPY --from=build /app/target/dimensions-0.0.1-SNAPSHOT.jar /app/dimensions.jar
CMD ["java", "-jar", "dimensions.jar"]


